# Generated by Django 3.0.5 on 2020-04-28 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_products_sku_code'),
        ('supplier', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('value', models.FloatField(default=0.0)),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_transfer', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.Branch')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('received_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0.0, help_text='Quantity received')),
                ('buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('current_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.Branch')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliveries.Delivery')),
                ('home_branch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_location', to='branches.Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Products')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
