# Generated by Django 3.0.5 on 2020-04-27 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_image', models.ImageField(blank=True, upload_to='product_image/')),
                ('quantity', models.IntegerField(default=0, help_text='Quantity in stock')),
                ('buying_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateTimeField(auto_now_add=True, null=True)),
                ('value', models.FloatField(default=0.0)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='branches.Branch')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to', to='branches.Branch')),
            ],
            options={
                'permissions': [('receive_transfer', 'Can receive transfer')],
            },
        ),
        migrations.CreateModel(
            name='TransferProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Products')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Transfer')),
            ],
        ),
        migrations.CreateModel(
            name='BranchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.Branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Products')),
            ],
        ),
    ]
