# Generated by Django 3.0.5 on 2020-04-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_sku_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchproduct',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
